export const CHANGE_DATA = 'SignUpPage/CHANGE_DATA'
export const CLEAR = 'SignUpPage/CLEAR'
export const REQUEST_ERROR = 'SignUpPage/REQUEST_ERROR'
export const REQUEST_SUCCESS = 'SignUpPage/REQUEST_SUCCESS'
export const SENDING_REQUEST = 'SignUpPage/SENDING_REQUEST'
export const SIGN_UP_REQUEST = 'SignUpPage/SIGN_UP_REQUEST'
export const TOGGLE_IS_SUBSCRIBED = 'SignUpPage/TOGGLE_IS_SUBSCRIBED'
export const TOGGLE_SHOW_PASSWORD = 'SignUpPage/TOGGLE_SHOW_PASSWORD'
