export const CLEAR_MESSAGE_ERRORS = 'SignInPage/CLEAR_MESSAGE_ERRORS'
export const SET_DATA = 'SignInPage/SET_DATA'
export const SET_ERRORS = 'SignInPage/SET_ERRORS'
export const SET_MESSAGE_TYPE = 'SignInPage/SET_MESSAGE_TYPE'
export const SIGN_IN_REQUEST = 'SignInPage/SIGN_IN_REQUEST'
export const TOGGLE_SHOW_PASSWORD = 'SignInPage/TOGGLE_SHOW_PASSWORD'
