export const CLEAR = 'SignInPage/CLEAR'
export const REQUEST_ERROR = 'SignInPage/REQUEST_ERROR'
export const SENDING_REQUEST = 'SignInPage/SENDING_REQUEST'
export const SET_DATA = 'SignInPage/SET_DATA'
export const SET_ERRORS = 'SignInPage/SET_ERRORS'
export const SIGN_IN_REQUEST = 'SignInPage/SIGN_IN_REQUEST'
export const TOGGLE_SHOW_PASSWORD = 'SignInPage/TOGGLE_SHOW_PASSWORD'
