export const CLEAR_STATE = 'CreateTeam/CLEAR_STATE'
export const CREATE_TEAM = 'CreateTeam/CREATE_TEAM'
export const SET_ERRORS = 'CreateTeam/SET_ERRORS'
export const SET_LOADING_PHOTO = 'CreateTeam/SET_LOADING_PHOTO'
export const SET_NOTIFICATION_MESSAGE = 'CreateTeam/SET_NOTIFICATION_MESSAGE'
