export const CLEAR_STATE = 'Venue/CLEAR_STATE'
export const GET_VENUE = 'Venue/GET_VENUE'
export const SET_LOADING_VENUE = 'Venue/SET_LOADING_VENUE'
export const SET_VENUE = 'Venue/SET_VENUE'
export const SET_WELCOME_VISIBILITY = 'Venue/SET_WELCOME_VISIBILITY'
