export const CLEAR_STATE = 'VenuePage/CLEAR_STATE'
export const GET_VENUE = 'VenuePage/GET_VENUE'
export const SET_NOTIFICATION_MESSAGE = 'VenuePage/SET_NOTIFICATION_MESSAGE'
export const SET_SHOW_CREATE_REVIEW = 'VenuePage/SET_SHOW_CREATE_REVIEW'
export const SET_VENUE = 'VenuePage/SET_VENUE'
