export const CLEAR_ERRORS = 'CreateTeam/CLEAR_ERRORS'
export const CLEAR_STATE = 'CreateTeam/CLEAR_STATE'
export const CREATE_AVATAR = 'CreateTeam/CREATE_AVATAR'
export const CREATE_TEAM = 'CreateTeam/CREATE_TEAM'
export const DELETE_AVATAR = 'CreateTeam/DELETE_AVATAR'
export const SET_AVATAR = 'CreateTeam/SET_AVATAR'
export const SET_ERRORS = 'CreateTeam/SET_ERRORS'
