export const CLEAR_MESSAGE_ERRORS = 'ResetPasswordPage/CLEAR_MESSAGE_ERRORS'
export const RESET_PASSWORD_REQUEST = 'ResetPasswordPage/RESET_PASSWORD_REQUEST'
export const SET_DATA = 'ResetPasswordPage/SET_DATA'
export const SET_ERRORS = 'ResetPasswordPage/SET_ERRORS'
export const SET_MESSAGE_TYPE = 'ResetPasswordPage/SET_MESSAGE_TYPE'
export const TOGGLE_SHOW_PASSWORD = 'ResetPasswordPage/TOGGLE_SHOW_PASSWORD'
