export const SET_ADDRESS = 'TopBar/SET_ADDRESS'
export const SET_KEYWORDS = 'TopBar/SET_KEYWORDS'
export const SET_SHOW_DROPDOWN = 'TopBar/SET_SHOW_DROPDOWN'
export const SIGN_OUT_REQUEST = 'TopBar/SIGN_OUT_REQUEST'
export const SET_NAME = 'TopBar/SET_NAME'
