export const CLEAR_QUERY = 'TopBar/CLEAR_QUERY'
export const SET_CURRENT_URL = 'TopBar/SET_CURRENT_URL'
export const SET_QUERY = 'TopBar/SET_QUERY'
export const SET_SHOW_DROPDOWN = 'TopBar/SET_SHOW_DROPDOWN'
export const SIGN_OUT_REQUEST = 'TopBar/SIGN_OUT_REQUEST'
