export const CLEAR_QUERY = 'TopBar/CLEAR_QUERY'
export const SET_QUERY = 'TopBar/SET_QUERY'
export const SET_SHOW_DROPDOWN = 'TopBar/SET_SHOW_DROPDOWN'
export const TOGGLE_SHOW_DROPDOWN = 'TopBar/TOGGLE_SHOW_DROPDOWN'
