export const CHANGE_AUTHENTICATED = 'App/CHANGE_AUTHENTICATED'
export const CHANGE_IS_AUTHENTICATING = 'App/CHANGE_IS_AUTHENTICATING'
export const CHANGE_USER_DATA = 'App/CHANGE_USER_DATA'
export const HANDLE_AUTHENTICATION = 'App/HANDLE_AUTHENTICATION'
